package reporter

import (
	"fmt"
	"html/template"
	"io"

	"shadiff/internal/model"
)

// HTMLReporter HTML 报告生成器
type HTMLReporter struct{}

func (r *HTMLReporter) Generate(results []model.DiffResult, summary model.DiffSummary, w io.Writer) error {
	data := struct {
		Summary model.DiffSummary
		Results []model.DiffResult
	}{
		Summary: summary,
		Results: results,
	}

	tmpl, err := template.New("report").Funcs(template.FuncMap{
		"severityClass": func(s model.Severity) string {
			switch s {
			case model.SeverityError:
				return "error"
			case model.SeverityWarning:
				return "warning"
			default:
				return "info"
			}
		},
		"pct": func(f float64) string {
			return fmt.Sprintf("%.1f", f*100)
		},
	}).Parse(htmlTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	return tmpl.Execute(w, data)
}

const htmlTemplate = `<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<title>Shadiff Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; background: #f5f5f5; color: #333; }
  h1 { color: #1a1a2e; }
  .summary { background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .summary .stat { display: inline-block; margin-right: 30px; }
  .summary .stat .value { font-size: 24px; font-weight: bold; }
  .summary .stat .label { color: #666; font-size: 14px; }
  .match-rate { color: #22c55e; }
  .record { background: white; padding: 16px; margin-bottom: 8px; border-radius: 6px; border-left: 4px solid #22c55e; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
  .record.has-diff { border-left-color: #ef4444; }
  .record .method { font-weight: bold; font-family: monospace; }
  .record .path { font-family: monospace; color: #555; }
  .record .status { float: right; font-weight: bold; }
  .record .status.match { color: #22c55e; }
  .record .status.diff { color: #ef4444; }
  .diffs { margin-top: 10px; padding-left: 20px; }
  .diff-item { padding: 4px 0; font-size: 14px; font-family: monospace; }
  .diff-item .path { color: #3b82f6; }
  .diff-item.ignored { color: #999; text-decoration: line-through; }
  .severity { font-size: 12px; padding: 2px 6px; border-radius: 3px; }
  .severity.error { background: #fee2e2; color: #dc2626; }
  .severity.warning { background: #fef3c7; color: #d97706; }
  .severity.info { background: #dbeafe; color: #2563eb; }
</style>
</head>
<body>
<h1>Shadiff Report</h1>

<div class="summary">
  <div class="stat">
    <div class="value">{{.Summary.TotalCount}}</div>
    <div class="label">总记录</div>
  </div>
  <div class="stat">
    <div class="value" style="color:#22c55e">{{.Summary.MatchCount}}</div>
    <div class="label">匹配</div>
  </div>
  <div class="stat">
    <div class="value" style="color:#ef4444">{{.Summary.DiffCount}}</div>
    <div class="label">差异</div>
  </div>
  <div class="stat">
    <div class="value match-rate">{{pct .Summary.MatchRate}}%</div>
    <div class="label">匹配率</div>
  </div>
</div>

{{range .Results}}
<div class="record {{if not .Match}}has-diff{{end}}">
  <span class="status {{if .Match}}match{{else}}diff{{end}}">
    {{if .Match}}MATCH{{else}}DIFF{{end}}
  </span>
  <span class="method">{{.Request.Method}}</span>
  <span class="path">{{.Request.Path}}</span>

  {{if not .Match}}
  <div class="diffs">
    {{range .Differences}}
    <div class="diff-item {{if .Ignored}}ignored{{end}}">
      {{if .Ignored}}
        <span class="path">{{.Path}}</span>: 忽略 ({{.Rule}})
      {{else}}
        <span class="path">{{.Path}}</span>: {{.Expected}} ≠ {{.Actual}}
        <span class="severity {{severityClass .Severity}}">{{.Severity}}</span>
      {{end}}
    </div>
    {{end}}
  </div>
  {{end}}
</div>
{{end}}

<p style="color:#999;font-size:12px;margin-top:30px;">Generated by Shadiff</p>
</body>
</html>`
