package cmd

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"shadiff/internal/capture"
	"shadiff/internal/daemon"
	"shadiff/internal/logger"
	"shadiff/internal/model"
	"shadiff/internal/storage"

	"github.com/spf13/cobra"
)

var (
	recordTarget   string
	recordListen   string
	recordSession  string
	recordDBProxy  []string
	recordDuration string
	recordDaemon   bool
	daemonChild    bool
)

var recordCmd = &cobra.Command{
	Use:   "record",
	Short: "Start traffic recording",
	Long: `Start an HTTP reverse proxy to record all requests/responses and database side effects passing through it.

Examples:
  shadiff record -t http://localhost:8080 -l :18080 -s "user-module-migration"
  shadiff record -t http://old-api:8080 --db-proxy mysql://:13306->:3306
  shadiff record -D -t http://localhost:8080 -l :18080 -s "bg-session"`,
	RunE: runRecord,
}

func init() {
	recordCmd.Flags().StringVarP(&recordTarget, "target", "t", "", "Target service address (required, e.g. http://localhost:8080)")
	recordCmd.Flags().StringVarP(&recordListen, "listen", "l", ":18080", "Proxy listen address")
	recordCmd.Flags().StringVarP(&recordSession, "session", "s", "", "Session name (auto-generated by default)")
	recordCmd.Flags().StringArrayVar(&recordDBProxy, "db-proxy", nil, "DB proxy (e.g. mysql://:13306->:3306)")
	recordCmd.Flags().StringVarP(&recordDuration, "duration", "d", "", "Maximum recording duration (e.g. 30m)")
	recordCmd.Flags().BoolVarP(&recordDaemon, "daemon", "D", false, "Run as background daemon")
	recordCmd.Flags().BoolVar(&daemonChild, "_daemon-child", false, "Internal: daemon child process")
	recordCmd.Flags().MarkHidden("_daemon-child")

	recordCmd.MarkFlagRequired("target")
	rootCmd.AddCommand(recordCmd)
}

func runRecord(cmd *cobra.Command, args []string) error {
	homeDir, _ := os.UserHomeDir()
	dataDir := homeDir + "/.shadiff"

	if recordDaemon {
		return runDaemonParent(cmd, dataDir)
	}

	return runRecordLoop(dataDir)
}

// runDaemonParent re-execs the current binary as a detached child process.
func runDaemonParent(cobraCmd *cobra.Command, dataDir string) error {
	// Create storage and session first so the child can use --session
	store, err := storage.NewFileStore(dataDir)
	if err != nil {
		return fmt.Errorf("failed to create storage: %w", err)
	}

	sessionName := recordSession
	if sessionName == "" {
		sessionName = fmt.Sprintf("record-%s", time.Now().Format("20060102-150405"))
	}

	session := &model.Session{
		Name:   sessionName,
		Status: model.SessionRecording,
		Source: model.EndpointConfig{
			BaseURL: recordTarget,
		},
		DaemonMode: true,
	}

	if err := store.Create(session); err != nil {
		return fmt.Errorf("failed to create session: %w", err)
	}

	sessionDir := filepath.Join(dataDir, "sessions", session.ID)

	// Build child command with the same executable
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("failed to find executable: %w", err)
	}

	childArgs := []string{
		"record",
		"--target", recordTarget,
		"--listen", recordListen,
		"--session", session.ID,
		"--_daemon-child",
	}
	if recordDuration != "" {
		childArgs = append(childArgs, "--duration", recordDuration)
	}
	for _, db := range recordDBProxy {
		childArgs = append(childArgs, "--db-proxy", db)
	}

	child := exec.Command(executable, childArgs...)

	// Redirect stdout/stderr to daemon log file
	logPath := filepath.Join(sessionDir, "daemon.log")
	logFile, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to create daemon log: %w", err)
	}
	child.Stdout = logFile
	child.Stderr = logFile

	// Platform-specific detach
	daemon.Detach(child)

	if err := child.Start(); err != nil {
		logFile.Close()
		return fmt.Errorf("failed to start daemon: %w", err)
	}
	logFile.Close()

	// Write PID file
	pid := child.Process.Pid
	if err := daemon.WritePID(sessionDir, pid); err != nil {
		return fmt.Errorf("failed to write pidfile: %w", err)
	}

	// Update session with PID
	session.PID = pid
	store.Update(session)

	fmt.Printf("Recording started in background (session: %s, PID: %d)\n", session.ID, pid)
	fmt.Printf("  Name:   %s\n", session.Name)
	fmt.Printf("  Listen: %s -> %s\n", recordListen, recordTarget)
	fmt.Printf("  Log:    %s\n", logPath)
	fmt.Println()
	fmt.Printf("Stop with: shadiff record stop -s %s\n", session.ID)

	return nil
}

// runRecordLoop runs the actual recording proxy (foreground or daemon child).
func runRecordLoop(dataDir string) error {
	isDaemonChild := daemonChild

	// Initialize logger
	if err := logger.Init(dataDir, isDaemonChild); err != nil {
		return fmt.Errorf("failed to initialize logger: %w", err)
	}
	defer logger.Close()

	// Create storage
	store, err := storage.NewFileStore(dataDir)
	if err != nil {
		return fmt.Errorf("failed to create storage: %w", err)
	}

	var session *model.Session

	if isDaemonChild {
		// In daemon child mode, the session was already created by the parent.
		// recordSession contains the session ID passed via --session.
		session, err = store.Get(recordSession)
		if err != nil {
			return fmt.Errorf("failed to load session %s: %w", recordSession, err)
		}
		session.PID = os.Getpid()
		store.Update(session)

		sessionDir := filepath.Join(dataDir, "sessions", session.ID)
		defer daemon.RemovePID(sessionDir)
	} else {
		// Foreground mode: create session as before
		sessionName := recordSession
		if sessionName == "" {
			sessionName = fmt.Sprintf("record-%s", time.Now().Format("20060102-150405"))
		}

		session = &model.Session{
			Name:   sessionName,
			Status: model.SessionRecording,
			Source: model.EndpointConfig{
				BaseURL: recordTarget,
			},
		}

		if err := store.Create(session); err != nil {
			return fmt.Errorf("failed to create session: %w", err)
		}

		fmt.Printf("Session created: %s (%s)\n", session.ID, session.Name)
	}

	// Create recorder
	recorder := capture.NewRecorder(session.ID, store)
	defer recorder.Stop()

	// Create proxy
	proxy, err := capture.NewProxy(recordTarget, recorder)
	if err != nil {
		return fmt.Errorf("failed to create proxy: %w", err)
	}

	// Start HTTP server
	server := &http.Server{
		Addr:    recordListen,
		Handler: proxy,
	}

	// Context and signal handling
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Handle timeout
	if recordDuration != "" {
		dur, err := time.ParseDuration(recordDuration)
		if err != nil {
			return fmt.Errorf("invalid duration: %w", err)
		}
		ctx, cancel = context.WithTimeout(ctx, dur)
		defer cancel()
	}

	// Signal handling
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)

	// Start server
	go func() {
		if !isDaemonChild {
			fmt.Printf("Recording proxy started: %s -> %s\n", recordListen, recordTarget)
			fmt.Println("Press Ctrl+C to stop recording...")
		}
		logger.Info("Recording proxy started",
			"listen", recordListen,
			"target", recordTarget,
			"session", session.ID,
			"daemon", isDaemonChild,
		)
		if err := server.ListenAndServe(); err != http.ErrServerClosed {
			logger.Error("server error", err)
		}
	}()

	// Wait for stop signal
	select {
	case <-sigCh:
		if !isDaemonChild {
			fmt.Println("\nStopping recording...")
		}
		logger.Info("Received stop signal", "session", session.ID)
	case <-ctx.Done():
		if !isDaemonChild {
			fmt.Println("\nRecording duration reached, stopping...")
		}
		logger.Info("Recording duration reached", "session", session.ID)
	}

	// Graceful shutdown
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer shutdownCancel()
	server.Shutdown(shutdownCtx)

	// Update session status
	recordCount := int(recorder.Count())
	session.Status = model.SessionCompleted
	session.RecordCount = recordCount
	session.PID = 0
	if err := store.Update(session); err != nil {
		logger.Error("update session failed", err)
	}

	if !isDaemonChild {
		fmt.Printf("Recording complete: %d records saved to session %s\n", recordCount, session.ID)
	}
	logger.Info("Recording complete",
		"session", session.ID,
		"records", recordCount,
	)

	return nil
}
