package cmd

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"shadiff/internal/capture"
	"shadiff/internal/logger"
	"shadiff/internal/model"
	"shadiff/internal/storage"

	"github.com/spf13/cobra"
)

var (
	recordTarget  string
	recordListen  string
	recordSession string
	recordDBProxy []string
	recordDuration string
)

var recordCmd = &cobra.Command{
	Use:   "record",
	Short: "Start traffic recording",
	Long: `Start an HTTP reverse proxy to record all requests/responses and database side effects passing through it.

Examples:
  shadiff record -t http://localhost:8080 -l :18080 -s "user-module-migration"
  shadiff record -t http://old-api:8080 --db-proxy mysql://:13306->:3306`,
	RunE: runRecord,
}

func init() {
	recordCmd.Flags().StringVarP(&recordTarget, "target", "t", "", "Target service address (required, e.g. http://localhost:8080)")
	recordCmd.Flags().StringVarP(&recordListen, "listen", "l", ":18080", "Proxy listen address")
	recordCmd.Flags().StringVarP(&recordSession, "session", "s", "", "Session name (auto-generated by default)")
	recordCmd.Flags().StringArrayVar(&recordDBProxy, "db-proxy", nil, "DB proxy (e.g. mysql://:13306->:3306)")
	recordCmd.Flags().StringVarP(&recordDuration, "duration", "d", "", "Maximum recording duration (e.g. 30m)")

	recordCmd.MarkFlagRequired("target")
	rootCmd.AddCommand(recordCmd)
}

func runRecord(cmd *cobra.Command, args []string) error {
	// Initialize logger
	homeDir, _ := os.UserHomeDir()
	dataDir := homeDir + "/.shadiff"
	if err := logger.Init(dataDir); err != nil {
		return fmt.Errorf("failed to initialize logger: %w", err)
	}
	defer logger.Close()

	// Create storage
	store, err := storage.NewFileStore(dataDir)
	if err != nil {
		return fmt.Errorf("failed to create storage: %w", err)
	}

	// Create session
	sessionName := recordSession
	if sessionName == "" {
		sessionName = fmt.Sprintf("record-%s", time.Now().Format("20060102-150405"))
	}

	session := &model.Session{
		Name:   sessionName,
		Status: model.SessionRecording,
		Source: model.EndpointConfig{
			BaseURL: recordTarget,
		},
	}

	if err := store.Create(session); err != nil {
		return fmt.Errorf("failed to create session: %w", err)
	}

	fmt.Printf("Session created: %s (%s)\n", session.ID, session.Name)

	// Create recorder
	recorder := capture.NewRecorder(session.ID, store)
	defer recorder.Stop()

	// Create proxy
	proxy, err := capture.NewProxy(recordTarget, recorder)
	if err != nil {
		return fmt.Errorf("failed to create proxy: %w", err)
	}

	// Start HTTP server
	server := &http.Server{
		Addr:    recordListen,
		Handler: proxy,
	}

	// Context and signal handling
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Handle timeout
	if recordDuration != "" {
		dur, err := time.ParseDuration(recordDuration)
		if err != nil {
			return fmt.Errorf("invalid duration: %w", err)
		}
		ctx, cancel = context.WithTimeout(ctx, dur)
		defer cancel()
	}

	// Signal handling
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)

	// Start server
	go func() {
		fmt.Printf("Recording proxy started: %s -> %s\n", recordListen, recordTarget)
		fmt.Println("Press Ctrl+C to stop recording...")
		if err := server.ListenAndServe(); err != http.ErrServerClosed {
			logger.Error("server error", err)
		}
	}()

	// Wait for stop signal
	select {
	case <-sigCh:
		fmt.Println("\nStopping recording...")
	case <-ctx.Done():
		fmt.Println("\nRecording duration reached, stopping...")
	}

	// Graceful shutdown
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer shutdownCancel()
	server.Shutdown(shutdownCtx)

	// Update session status
	recordCount := int(recorder.Count())
	session.Status = model.SessionCompleted
	session.RecordCount = recordCount
	if err := store.Update(session); err != nil {
		logger.Error("update session failed", err)
	}

	fmt.Printf("Recording complete: %d records saved to session %s\n", recordCount, session.ID)
	return nil
}
